services:
  - type: web
    name: chemical-rss-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python production_server.py
    healthCheckPath: /api/summary
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: false 